version: 2
jobs:
  build:
    docker:
      - image: golang:1.18
    working_directory: /projects/dataloaden
    steps: &steps
      - checkout
      - run: go generate ./example/... && if [[ $(git diff) ]] ; then echo "you need to run go generate" ; git diff ; exit 1 ; fi
      - run: go test -bench=. -benchmem -v ./example/...
      - run: go test -bench=. -benchmem -v ./example/... -race
      - run: go test -coverprofile=coverage.txt -covermode=atomic ./example && bash <(curl -s https://codecov.io/bash)
